version: "3.3"
services:
  f1whendev:
    container_name: "f1whendev"
    image: cosmtrek/air
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - "8081:8081"
    environment:
      - DEV=true
